apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: weigoldl-frontend
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/frontend
      jib:
        args:
          - -Dmaven.test.skip=true
deploy:
  helm:
    releases:
      - name: weigoldl-frontend
        chartPath: src/charts/frontend
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/frontend




