kubernetesPipeline {
 scmUrl = 'https://gitlab.informatik.hs-furtwangen.de/cnc/weigoldl-hasher.git'
 containerImage = 'docker.informatik.hs-furtwangen.de/cnc-weigoldl/hasher'
 chartPath = './src/charts/hasher'
 releaseName = 'weigoldl-hasher'
 stagingNamespace = 'cnc'
 branch = 'main'
}
