apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: weigoldl-hasher
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/hasher
      jib:
        args:
          - -Dmaven.test.skip=true
deploy:
  helm:
    releases:
      - name: weigoldl-hasher
        chartPath: src/charts/hasher
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/hasher




