kubernetesPipeline {
 scmUrl = 'https://gitlab.informatik.hs-furtwangen.de/cnc/weigoldl-randomizer.git'
 containerImage = 'docker.informatik.hs-furtwangen.de/cnc-weigoldl/randomizer'
 chartPath = './src/charts/randomizer'
 releaseName = 'weigoldl-randomizer'
 stagingNamespace = 'cnc'
 branch = 'main'
}
