# Get pods with 'kubectl get pods -l author=weigoldl,app=randomizer'
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: weigoldl-randomizer
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/randomizer
      jib:
        args:
          - -Dmaven.test.skip=true
deploy:
  helm:
    releases:
      - name: weigoldl-randomizer
        chartPath: src/charts/randomizer
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/randomizer




