replicaCount: 2
image: docker.informatik.hs-furtwangen.de/cnc-weigoldl/worker:latest
app: worker
author: weigoldl
requestMem: 32Mi
limitMem: 256Mi
mongodb:
  podLabels:
    author: weigoldl
  extraFlags:
    - "--wiredTigerEngineConfigString=log=(prealloc=false,file_max=20MB)"
    - "--setParameter diagnosticDataCollectionEnabled=false"
  auth:
    enabled: false
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
