apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-{{ .Values.app }}-{{ .Values.author }}
  labels:
    app: {{ .Values.app }}
    author: {{ .Values.author }}
spec:
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: web
  selector:
    matchLabels:
      app: {{ .Values.app }}
      author: {{ .Values.author }}
