kubernetesPipeline {
 scmUrl = 'https://gitlab.informatik.hs-furtwangen.de/cnc/weigoldl-worker.git'
 containerImage = 'docker.informatik.hs-furtwangen.de/cnc-weigoldl/worker'
 chartPath = './src/charts/worker'
 releaseName = 'weigoldl-worker'
 stagingNamespace = 'cnc'
 branch = 'main'
}